module.exports = {
  apps: [
    {
      name: "xrp-alert",
      script: "monitor.js",
      cwd: __dirname,
      interpreter: "node",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      restart_delay: 5000,
      watch: false,
      max_memory_restart: "150M",
      time: true,
      env: {
        NODE_ENV: "production",
        TELEGRAM_ALERT_CHAT_ID: "-5363003109",
        TELEGRAM_DAILY_CHAT_ID: "-5535517204",
        ASPECTA_ENABLED: "true",
        ASPECTA_KLINE_URL: "https://aspecta.ai/api/hermes/trading/k-line",
        ASPECTA_MONITORED_ASSETS: "Ostium,DAPPOS",
        ASPECTA_CHECK_INTERVAL_MS: "300000",
        ASPECTA_CHANGE_THRESHOLD_PERCENT: "10",
        ASPECTA_REPEAT_PRICE_DELTA_PERCENT: "5",
        ASPECTA_REPEAT_ALERT_WINDOW_HOURS: "24",
        ASPECTA_REPEAT_PRICE_DELTA_PERCENT_AFTER_10_ALERTS: "10",
        ASPECTA_REPEAT_PRICE_DELTA_PERCENT_AFTER_20_ALERTS: "20",
        ASPECTA_PRICE_DECIMALS: "18",
      },
    },
  ],
};
